### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [RumbleTalk/moodle-mod_rumbletalkchat#13]
previously reported in #5 - as mentioned there, this is a blocker for plugin db approval, 

Please take close note of the "External location" part of the privacy api which will need to be implemented in your plugin:
https://moodledev.io/docs/apis/subsystems/privacy/#indicating-that-you-export-data-to-an-external-location

**Comment by jeirod** [comment]
Hi @danmarsden, We added a provider.php and placed it in classes/privacy. In accordance with the documentation of privacy, we also add privacy strings in the language folder.
Please note, the chat service is GDPR related see here https://rumbletalk.com/about_us/privacy_policy/.
