### ISSUE TITLE
invalid debugging class storing log data in webroot

### ISSUE THREAD

**Issue by danmarsden** [RumbleTalk/moodle-mod_rumbletalkchat#16]
Your debugging class appears to try and write to the webroot - this is not typically allowed (many moodle sites will have server permisssions that block this) and it is considered a security risk - if you really need to store debug/logging data you should get it to store within moodledata, not the webroot.

https://github.com/RumbleTalk/moodle-mod_rumbletalkchat/blob/main/classes/local/debugging.php#L32

**Comment by jeirod** [comment]
Hi @danmarsden, we have removed the debugging.php and the directory folder of local. The debugging part was for testing purposes only.
