### ISSUE TITLE
Language strings must not be hard-coded in english

### ISSUE THREAD

**Issue by danmarsden** [RumbleTalk/moodle-mod_rumbletalkchat#4]
All user-facing strings must sit within the lang pack - your plugin contains many hard-coded english language strings - this is a blocker for approval in the moodle.org plugins db and must be fixed prior to approval.

more info here:
https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

**Comment by jeirod** [comment]
Ok, we replaced the hard-coded strings with get_string() and these strings are put in the language folder. (moodle-block-group-chat/lang/en/block_rumbletalk_chat.php).
