### ISSUE TITLE
Missing privacy API

### ISSUE THREAD

**Issue by danmarsden** [RumbleTalk/moodle-mod_rumbletalkchat#5]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin passes user information to an external service and so must implement the api and document what is passed to the external service (I could see at least email and username being passed.)

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note - as this appears to be a commercial plugin this is a blocker for approval in the plugins db.

**Comment by jeirod** [comment]
We added a provider.php and placed it in classes/privacy. In accordance with the documentation of privacy, we also add privacy strings in the language folder.
Please note, the chat service is GDPR related see here https://rumbletalk.com/about_us/privacy_policy/.

**Comment by danmarsden** [comment]
Looks like privacy provider is still missing? - note this is a blocker for plugins db approval.
