### ISSUE TITLE
moodle.org plugin entry must prominently state that your plugin is commercial

### ISSUE THREAD

**Issue by danmarsden** [RumbleTalk/moodle-mod_rumbletalkchat#7]
Within the first few lines of your plugins db description, you must make it extremely clear that your plugin requires a commercial subscription to be used (it's not a free plugin that works on it's own within Moodle) - this is typically done with a statment something like the following near the top of the plugins db description.

 you must have a paid subscription to be able to use this plugin.

**Comment by jeirod** [comment]
The RumbleTalk plugin is free. The free version has some limitations but most users use it as is. The commercial part includes an upgraded version with all features open. We have added a description about this at readme.txt, readme.md, and at our plugin on the directory (​​https://moodle.org/plugins/block_rumbletalk_chat).
