### ISSUE TITLE
Please review namespacing/class naming rules

### ISSUE THREAD

**Issue by danmarsden** [RumbleTalk/moodle-mod_rumbletalkchat#8]
Class names like "create_account_form" are incorrect - forms should sit within the classes/forms folder in your plugin and use correct namespacing:
https://docs.moodle.org/dev/Automatic_class_loading

more useful info: https://docs.moodle.org/dev/Frankenstyle

please note - this is a blocker for approval in the plugins db - class and function names must follow our naming conventions to prevent clashing with core code.

**Comment by jeirod** [comment]
We change the class name and file name of "create_account_form" to “create_form”. Also, we made a folder classes/forms to contain all of the possible forms which are used in our plugin.

**Comment by danmarsden** [comment]
Hi there - sorry for the delay in coming back to this but it doens't appear you have understood our naming rules. a class called "create_form" is incorrect.
It should be namepsaced like "block_rumbletalk_chat\forms\create_form"
or... be prefixed with your frankenstyle name like:
"block_rumbletalk_chat_create_form"

unforutnatlely this still blocks approval of your plugin.
